/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this */
package cleanenergy;

/**
 *
 * @author jordancarthy
 */
public class carbonGUI extends javax.swing.JFrame {

    /**
     * Creates new form carbonGUI
     */
    public carbonGUI() {
        initComponents();
      TransportPane.setVisible(false);
      recyclingPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalCarbonFootprintLBL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        billsPane = new javax.swing.JLayeredPane();
        carbonBillsLBL = new javax.swing.JLabel();
        elctricBillLBL = new javax.swing.JLabel();
        electricBillTF = new javax.swing.JTextField();
        firstQuestionVAR = new javax.swing.JLabel();
        gasBillTF = new javax.swing.JTextField();
        oilBillLBL = new javax.swing.JLabel();
        oilBillTF = new javax.swing.JTextField();
        billsEnterBTN = new javax.swing.JButton();
        TransportPane = new javax.swing.JLayeredPane();
        transportLBL = new javax.swing.JLabel();
        flightsLessFourLBL = new javax.swing.JLabel();
        flightsMoreFourLBL = new javax.swing.JLabel();
        carYearlyMileageLBL = new javax.swing.JLabel();
        flightLessFourTF = new javax.swing.JTextField();
        flightMoreFourTF = new javax.swing.JTextField();
        carYearlyMileageTF = new javax.swing.JTextField();
        transportEnterBTN = new javax.swing.JButton();
        recyclingPane = new javax.swing.JLayeredPane();
        recyclingLBL = new javax.swing.JLabel();
        newsPaperCB = new javax.swing.JCheckBox();
        alumCB = new javax.swing.JCheckBox();
        recyclingBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carbon Footprint");
        setPreferredSize(new java.awt.Dimension(611, 377));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalCarbonFootprintLBL.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        totalCarbonFootprintLBL.setText("Total Carbon Footprint : 0 punds of C02");
        getContentPane().add(totalCarbonFootprintLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 192, -1));

        backBTN.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carbonBillsLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        carbonBillsLBL.setText("Carbon bills");

        elctricBillLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        elctricBillLBL.setText("Electric Bill Monthly :");

        electricBillTF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        firstQuestionVAR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        firstQuestionVAR.setText("Gas Bill Monthly :");

        gasBillTF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        oilBillLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        oilBillLBL.setText("Oil Bill Monthly :");

        oilBillTF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        billsEnterBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        billsEnterBTN.setLabel("Enter");
        billsEnterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsEnterBTNActionPerformed(evt);
            }
        });

        billsPane.setLayer(carbonBillsLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        billsPane.setLayer(elctricBillLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        billsPane.setLayer(electricBillTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        billsPane.setLayer(firstQuestionVAR, javax.swing.JLayeredPane.DEFAULT_LAYER);
        billsPane.setLayer(gasBillTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        billsPane.setLayer(oilBillLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        billsPane.setLayer(oilBillTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        billsPane.setLayer(billsEnterBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout billsPaneLayout = new javax.swing.GroupLayout(billsPane);
        billsPane.setLayout(billsPaneLayout);
        billsPaneLayout.setHorizontalGroup(
            billsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billsPaneLayout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addGroup(billsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billsPaneLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(carbonBillsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billsPaneLayout.createSequentialGroup()
                        .addComponent(elctricBillLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(electricBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billsPaneLayout.createSequentialGroup()
                        .addComponent(firstQuestionVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(gasBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billsPaneLayout.createSequentialGroup()
                        .addComponent(oilBillLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(oilBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billsPaneLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(billsEnterBTN)))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        billsPaneLayout.setVerticalGroup(
            billsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billsPaneLayout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(carbonBillsLBL)
                .addGap(8, 8, 8)
                .addGroup(billsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elctricBillLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(billsPaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(electricBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(billsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstQuestionVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(billsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oilBillLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oilBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(billsEnterBTN)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jPanel1.add(billsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 440, 260));

        TransportPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                TransportPaneComponentHidden(evt);
            }
        });

        transportLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        transportLBL.setText("Transport");

        flightsLessFourLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        flightsLessFourLBL.setText("Amount of flights that are less than 4 hours :");

        flightsMoreFourLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        flightsMoreFourLBL.setText("Amount of flights that were more than 4 hours :");

        carYearlyMileageLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        carYearlyMileageLBL.setText("Cars yearly mileage :");

        flightLessFourTF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        flightMoreFourTF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        carYearlyMileageTF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        transportEnterBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        transportEnterBTN.setLabel("Enter");
        transportEnterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportEnterBTNActionPerformed(evt);
            }
        });

        TransportPane.setLayer(transportLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TransportPane.setLayer(flightsLessFourLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TransportPane.setLayer(flightsMoreFourLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TransportPane.setLayer(carYearlyMileageLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TransportPane.setLayer(flightLessFourTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TransportPane.setLayer(flightMoreFourTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TransportPane.setLayer(carYearlyMileageTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TransportPane.setLayer(transportEnterBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TransportPaneLayout = new javax.swing.GroupLayout(TransportPane);
        TransportPane.setLayout(TransportPaneLayout);
        TransportPaneLayout.setHorizontalGroup(
            TransportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransportPaneLayout.createSequentialGroup()
                .addGroup(TransportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransportPaneLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(TransportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TransportPaneLayout.createSequentialGroup()
                                .addComponent(carYearlyMileageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(transportEnterBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(flightLessFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flightMoreFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flightsMoreFourLBL)
                            .addComponent(carYearlyMileageLBL)
                            .addComponent(flightsLessFourLBL)))
                    .addGroup(TransportPaneLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(transportLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(3476, Short.MAX_VALUE))
        );
        TransportPaneLayout.setVerticalGroup(
            TransportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransportPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transportLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightsLessFourLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightLessFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(flightsMoreFourLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightMoreFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(carYearlyMileageLBL)
                .addGap(18, 18, 18)
                .addGroup(TransportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transportEnterBTN)
                    .addComponent(carYearlyMileageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(TransportPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        recyclingLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        recyclingLBL.setText("Recycling");

        newsPaperCB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        newsPaperCB.setText("Do you recycle Newspaper");
        newsPaperCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsPaperCBActionPerformed(evt);
            }
        });

        alumCB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        alumCB.setText("Do you recycle aluminum");
        alumCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumCBActionPerformed(evt);
            }
        });

        recyclingBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        recyclingBTN.setLabel("Submit");
        recyclingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recyclingBTNActionPerformed(evt);
            }
        });

        recyclingPane.setLayer(recyclingLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        recyclingPane.setLayer(newsPaperCB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        recyclingPane.setLayer(alumCB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        recyclingPane.setLayer(recyclingBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout recyclingPaneLayout = new javax.swing.GroupLayout(recyclingPane);
        recyclingPane.setLayout(recyclingPaneLayout);
        recyclingPaneLayout.setHorizontalGroup(
            recyclingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recyclingPaneLayout.createSequentialGroup()
                .addGroup(recyclingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recyclingPaneLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(recyclingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alumCB)
                            .addComponent(newsPaperCB)
                            .addGroup(recyclingPaneLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(recyclingBTN))))
                    .addGroup(recyclingPaneLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(recyclingLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(3547, Short.MAX_VALUE))
        );
        recyclingPaneLayout.setVerticalGroup(
            recyclingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recyclingPaneLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(recyclingLBL)
                .addGap(32, 32, 32)
                .addComponent(newsPaperCB)
                .addGap(18, 18, 18)
                .addComponent(alumCB)
                .addGap(25, 25, 25)
                .addComponent(recyclingBTN)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jPanel1.add(recyclingPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alumCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumCBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_alumCBActionPerformed

    private void newsPaperCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsPaperCBActionPerformed
        // TODO add your handling code here:
      
      
            
       
    }//GEN-LAST:event_newsPaperCBActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        CleanEnergyGUI mainGUI = new CleanEnergyGUI(); 
        mainGUI.setVisible(true); 
        this.setVisible(false); 
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void billsEnterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsEnterBTNActionPerformed
        // TODO add your handling code here:
        billsPane.setVisible(false);
        TransportPane.setVisible(true);
        
    }//GEN-LAST:event_billsEnterBTNActionPerformed

    private void TransportPaneComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TransportPaneComponentHidden
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TransportPaneComponentHidden

    private void transportEnterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportEnterBTNActionPerformed
        // TODO add your handling code here:
        TransportPane.setVisible(false);
        recyclingPane.setVisible(true);
    }//GEN-LAST:event_transportEnterBTNActionPerformed

    private void recyclingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recyclingBTNActionPerformed
        // TODO add your handling code here:
        recyclingPane.setVisible(false);
    }//GEN-LAST:event_recyclingBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carbonGUI().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane TransportPane;
    private javax.swing.JCheckBox alumCB;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton billsEnterBTN;
    private javax.swing.JLayeredPane billsPane;
    private javax.swing.JLabel carYearlyMileageLBL;
    private javax.swing.JTextField carYearlyMileageTF;
    private javax.swing.JLabel carbonBillsLBL;
    private javax.swing.JLabel elctricBillLBL;
    private javax.swing.JTextField electricBillTF;
    private javax.swing.JLabel firstQuestionVAR;
    private javax.swing.JTextField flightLessFourTF;
    private javax.swing.JTextField flightMoreFourTF;
    private javax.swing.JLabel flightsLessFourLBL;
    private javax.swing.JLabel flightsMoreFourLBL;
    private javax.swing.JTextField gasBillTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox newsPaperCB;
    private javax.swing.JLabel oilBillLBL;
    private javax.swing.JTextField oilBillTF;
    private javax.swing.JButton recyclingBTN;
    private javax.swing.JLabel recyclingLBL;
    private javax.swing.JLayeredPane recyclingPane;
    private javax.swing.JLabel totalCarbonFootprintLBL;
    private javax.swing.JButton transportEnterBTN;
    private javax.swing.JLabel transportLBL;
    // End of variables declaration//GEN-END:variables
}
