/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this */
package cleanenergy;

/**
 *
 * @author jordancarthy
 */
public class carbonGUI extends javax.swing.JFrame {

    /**
     * Creates new form carbonGUI
     */
    public carbonGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        carbonBillsLBL = new javax.swing.JLabel();
        recyclingLBL = new javax.swing.JLabel();
        transportLBL = new javax.swing.JLabel();
        newsPaperCB = new javax.swing.JCheckBox();
        alumCB = new javax.swing.JCheckBox();
        totalCarbonFootprintLBL = new javax.swing.JLabel();
        elctricBillLBL = new javax.swing.JLabel();
        electricBillTF = new javax.swing.JTextField();
        gasBillLBL = new javax.swing.JLabel();
        gasBillTF = new javax.swing.JTextField();
        oilBillLBL = new javax.swing.JLabel();
        oilBillTF = new javax.swing.JTextField();
        flightsLessFourLBL = new javax.swing.JLabel();
        flightsMoreFourLBL = new javax.swing.JLabel();
        carYearlyMileageLBL = new javax.swing.JLabel();
        flightLessFourTF = new javax.swing.JTextField();
        flightMoreFourTF = new javax.swing.JTextField();
        carYearlyMileageTF = new javax.swing.JTextField();
        billsEnterBTN = new javax.swing.JButton();
        transportEnterBTN = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(611, 377));
        setResizable(false);

        carbonBillsLBL.setText("Carbon bills");

        recyclingLBL.setText("Recycling");

        transportLBL.setText("Transport");

        newsPaperCB.setText("Do you recycle Newspaper");
        newsPaperCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsPaperCBActionPerformed(evt);
            }
        });

        alumCB.setText("Do you recycle aluminum");
        alumCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumCBActionPerformed(evt);
            }
        });

        totalCarbonFootprintLBL.setText("Total Carbon Footprint : 0 punds of C02");

        elctricBillLBL.setText("Electric Bill Monthly :");

        gasBillLBL.setText("Gas Bill Monthly :");

        oilBillLBL.setText("Oil Bill Monthly :");

        flightsLessFourLBL.setText("Amount of flights that are less than 4 hours :");

        flightsMoreFourLBL.setText("Amount of flights that were more than 4 hours :");

        carYearlyMileageLBL.setText("Cars yearly mileage :");

        billsEnterBTN.setLabel("Enter");

        transportEnterBTN.setLabel("Enter");

        jButton3.setLabel("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alumCB)
                            .addComponent(newsPaperCB)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(carbonBillsLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(transportLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(recyclingLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(flightsLessFourLBL)
                            .addComponent(flightLessFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flightMoreFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(carYearlyMileageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(transportEnterBTN))
                            .addComponent(flightsMoreFourLBL)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(carYearlyMileageLBL)
                                .addGap(126, 126, 126)
                                .addComponent(totalCarbonFootprintLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(elctricBillLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gasBillLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oilBillLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(oilBillTF, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(gasBillTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(electricBillTF, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(44, 44, 44)
                                .addComponent(billsEnterBTN)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(carbonBillsLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elctricBillLBL)
                    .addComponent(electricBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gasBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasBillLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oilBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billsEnterBTN)
                    .addComponent(oilBillLBL))
                .addGap(40, 40, 40)
                .addComponent(recyclingLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newsPaperCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumCB)
                    .addComponent(jButton3))
                .addGap(9, 9, 9)
                .addComponent(transportLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightsLessFourLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightLessFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(flightsMoreFourLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(flightMoreFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carYearlyMileageLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carYearlyMileageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(totalCarbonFootprintLBL)
                        .addGap(18, 18, 18)
                        .addComponent(transportEnterBTN)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alumCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumCBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_alumCBActionPerformed

    private void newsPaperCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsPaperCBActionPerformed
        // TODO add your handling code here:
      
      
            
       
    }//GEN-LAST:event_newsPaperCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carbonGUI().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alumCB;
    private javax.swing.JButton billsEnterBTN;
    private javax.swing.JLabel carYearlyMileageLBL;
    private javax.swing.JTextField carYearlyMileageTF;
    private javax.swing.JLabel carbonBillsLBL;
    private javax.swing.JLabel elctricBillLBL;
    private javax.swing.JTextField electricBillTF;
    private javax.swing.JTextField flightLessFourTF;
    private javax.swing.JTextField flightMoreFourTF;
    private javax.swing.JLabel flightsLessFourLBL;
    private javax.swing.JLabel flightsMoreFourLBL;
    private javax.swing.JLabel gasBillLBL;
    private javax.swing.JTextField gasBillTF;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JCheckBox newsPaperCB;
    private javax.swing.JLabel oilBillLBL;
    private javax.swing.JTextField oilBillTF;
    private javax.swing.JLabel recyclingLBL;
    private javax.swing.JLabel totalCarbonFootprintLBL;
    private javax.swing.JButton transportEnterBTN;
    private javax.swing.JLabel transportLBL;
    // End of variables declaration//GEN-END:variables
}
