/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cleanenergy;

/**
 *
 * @author jordancarthy
 */
public class CleanEnergyGUI extends javax.swing.JFrame {

    /**
     * Creates new form CleanEnergyGUI
     */
    public CleanEnergyGUI() {
        initComponents();
        mainGuiScrollP.getViewport().setOpaque(false);
        //https://stackoverflow.com/questions/30435186/how-to-make-jtextarea-transparent-background 
        mainGuiIntroTA.setText(" Empower your journey to sustainability with our Clean Energy app—featuring a carbon calculator, interactive game, and educational quiz!");
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainGuiBTNGroup = new javax.swing.ButtonGroup();
        javax.swing.JButton calcBTN = new javax.swing.JButton();
        javax.swing.JButton gameBTN = new javax.swing.JButton();
        quizBTN = new javax.swing.JButton();
        exitMainBTN = new javax.swing.JButton();
        mainTitleLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainGuiScrollP = new javax.swing.JScrollPane();
        mainGuiIntroTA = new javax.swing.JTextArea();
        backgroundIMGLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));
        setForeground(new java.awt.Color(255, 204, 51));
        setMinimumSize(new java.awt.Dimension(609, 374));
        setPreferredSize(new java.awt.Dimension(609, 374));
        getContentPane().setLayout(null);

        calcBTN.setBackground(new java.awt.Color(57, 39, 56, 20));
        calcBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cleanenergy/calcImage.png"))); // NOI18N
        calcBTN.setBorderPainted(false);
        mainGuiBTNGroup.add(calcBTN);
        calcBTN.setContentAreaFilled(false);
        calcBTN.setFocusPainted(false);
        calcBTN.setFocusTraversalKeysEnabled(false);
        calcBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBTNActionPerformed(evt);
            }
        });
        getContentPane().add(calcBTN);
        calcBTN.setBounds(70, 190, 90, 100);

        gameBTN.setBackground(new java.awt.Color(57, 39, 56, 20));
        gameBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cleanenergy/gameImage.png"))); // NOI18N
        gameBTN.setBorderPainted(false);
        mainGuiBTNGroup.add(gameBTN);
        gameBTN.setContentAreaFilled(false);
        gameBTN.setFocusPainted(false);
        gameBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameBTNActionPerformed(evt);
            }
        });
        getContentPane().add(gameBTN);
        gameBTN.setBounds(230, 190, 110, 100);

        quizBTN.setBackground(new java.awt.Color(57, 39, 56, 20));
        quizBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cleanenergy/quizImage.png"))); // NOI18N
        quizBTN.setBorderPainted(false);
        mainGuiBTNGroup.add(quizBTN);
        quizBTN.setContentAreaFilled(false);
        quizBTN.setFocusPainted(false);
        quizBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBTNActionPerformed(evt);
            }
        });
        getContentPane().add(quizBTN);
        quizBTN.setBounds(400, 190, 110, 100);

        exitMainBTN.setBackground(new java.awt.Color(255, 51, 51));
        exitMainBTN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exitMainBTN.setForeground(new java.awt.Color(255, 255, 255));
        exitMainBTN.setText("Exit");
        exitMainBTN.setFocusTraversalKeysEnabled(false);
        exitMainBTN.setFocusable(false);
        exitMainBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMainBTNActionPerformed(evt);
            }
        });
        getContentPane().add(exitMainBTN);
        exitMainBTN.setBounds(20, 300, 84, 23);

        mainTitleLBL.setBackground(new java.awt.Color(255, 255, 255));
        mainTitleLBL.setFont(new java.awt.Font("Lucida Grande", 3, 36)); // NOI18N
        mainTitleLBL.setForeground(new java.awt.Color(255, 255, 255));
        mainTitleLBL.setText("Clean Energy");
        getContentPane().add(mainTitleLBL);
        mainTitleLBL.setBounds(170, 20, 300, 43);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("This is our CleanEnergyApp,\n We hope to fuel future generations and current generations,\nBy providing a fun and engaging way of learning about how we can make a cleaner future ! ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 80, 0, 10);

        mainGuiScrollP.setBackground(new java.awt.Color(255, 255, 255, 20));
        mainGuiScrollP.setBorder(null);
        mainGuiScrollP.setForeground(new java.awt.Color(255, 255, 255, 20));
        mainGuiScrollP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        mainGuiScrollP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        mainGuiScrollP.setOpaque(false);

        mainGuiIntroTA.setEditable(false);
        mainGuiIntroTA.setBackground(new java.awt.Color(57, 39, 56, 20));
        mainGuiIntroTA.setColumns(20);
        mainGuiIntroTA.setFont(new java.awt.Font("Gujarati Sangam MN", 0, 12)); // NOI18N
        mainGuiIntroTA.setForeground(new java.awt.Color(255, 255, 255));
        mainGuiIntroTA.setLineWrap(true);
        mainGuiIntroTA.setRows(5);
        mainGuiIntroTA.setWrapStyleWord(true);
        mainGuiIntroTA.setAutoscrolls(false);
        mainGuiIntroTA.setBorder(null);
        mainGuiIntroTA.setOpaque(false);
        mainGuiScrollP.setViewportView(mainGuiIntroTA);

        getContentPane().add(mainGuiScrollP);
        mainGuiScrollP.setBounds(170, 70, 260, 120);

        backgroundIMGLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cleanenergy/sunrise-7674594_640.jpg"))); // NOI18N
        getContentPane().add(backgroundIMGLBL);
        backgroundIMGLBL.setBounds(0, 0, 650, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBTNActionPerformed
        // TODO add your handling code here:
        CarbonGUI calc = new CarbonGUI(); 
        calc.setVisible(true); //show
        calc.setOpacity(1);
        
        this.setVisible(false); //hide this
        System.out.println("closed"); //testing line
        //this.setDefaultCloseOperation(MainAppGUI.EXIT_ON_CLOSE);
        this.dispose(); //closes this frame as opposed to setVisible(false);
        
    }//GEN-LAST:event_calcBTNActionPerformed

    private void gameBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameBTNActionPerformed
        // TODO add your handling code here:
        GameGUI game = new GameGUI(); //declare and create
        game.setVisible(true); //show
        
        this.setVisible(false); //hide this
        System.out.println("closed"); //testing line
        //this.setDefaultCloseOperation(MainAppGUI.EXIT_ON_CLOSE);
        this.dispose(); //closes this frame as opposed to setVisible(false);
    }//GEN-LAST:event_gameBTNActionPerformed

    private void quizBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBTNActionPerformed
        // TODO add your handling code here:
        QuizGUI quiz = new QuizGUI(); 
        quiz.setVisible(true); 
        this.setVisible(false);
        this.dispose(); 
    }//GEN-LAST:event_quizBTNActionPerformed

    private void exitMainBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMainBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMainBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CleanEnergyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CleanEnergyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CleanEnergyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CleanEnergyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CleanEnergyGUI().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundIMGLBL;
    private javax.swing.JButton exitMainBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup mainGuiBTNGroup;
    private javax.swing.JTextArea mainGuiIntroTA;
    private javax.swing.JScrollPane mainGuiScrollP;
    private javax.swing.JLabel mainTitleLBL;
    private javax.swing.JButton quizBTN;
    // End of variables declaration//GEN-END:variables
}
